var xlat = {
  "en": {
      "record.contrib.info_text": "Don't worry, we're not big fans of spam either.  This information is required so we can notify you when your video is on display. We will not use it for any other purposes.",
      "record.contrib.or": "or",
      "record.contrib.please_login": "Please login via Facebook.",
      "record.contrib.first_name": "First name:",
      "record.contrib.last_name": "Last name:",
      "record.contrib.gender": "Gender:",
      "record.contrib.gender_m": "M",
      "record.contrib.gender_f": "F",
      "record.contrib.birthday": "Birthday:",
      "record.contrib.birthdate": "Birth date:",
      "record.contrib.birth_year": "Year of birth:",
      "record.contrib.country": "Country:",
      "record.contrib.state": "State:",
      "record.contrib.zip_code": "Zip code:",
      "record.contrib.email": "Email:",
      "record.contrib.optin": "Yes, sign me up for news and updates.",
      "record.contrib.age_gate.error": "Sorry, you must be {age} or older to submit a video.",
      "record.contrib.by_clicking_1": "I have read and agree to the VideoGenie",
      "record.contrib.tos": "Terms of Service and Privacy Policy",
      "record.contrib.by_clicking_2": ".",
      "record.contrib.i_accept": "Submit Video",
      "record.success.thankyou": "Thank you!",
      "record.success.we_ll_review": "We'll review your video shortly, and let you know as soon as your video is approved.",
      "record.vidinfo.almost_done": "You're almost done. Submit your video and share your inspiration with the world.",
      "record.vidinfo.tag_a_friend": "Tag a friend:",
      "record.vidinfo.video_title": "Video title:",
      "record.vidinfo.category": "Category:",
      "record.vidinfo.upload_video": "Upload a video instead",
      "record.fbshare.meantime": "In the meantime, you can share your video with your friends!",
      "record.fbshare.share_prompt": "Share your inspiration with your friends.",
      "record.fbshare.caption": "I shared my inspiration on Levi's FreeForum.",
      "record.fbshare.description": "Now's your chance to give a shout-out to your mentor, your muse, or even a friend who has inspired you in some way.  Share your message with the world- you never know who you'll inspire in return.",
      "record.fbshare.record_your_own": "Record your own",
      "record.tweet.by_clicking_1": "By approving the use of this tweet, you agree to the ",
      "record.tweet.by_clicking_2": ".",

      "redirect.on": "on",
      "redirect.facebook.campaign.description": "VideoGenie Video",

      "player.loading": "Loading",
      "player.you_need_flash": "You need Flash in order to see the videos.",
      "player.no_videos": "There are no videos yet.",
      "player.no_videos_in_cat": "There are no videos in this category.",
      "player.video_title": "Title:",
      "player.video_category": "Category:",
      "player.already_voted": "Oops, it looks like you've already voted for today. Please check back tomorrow (i.e., 24 hours) and vote again!",
      "player.problem_voting": "Sorry. There was a problem sending your vote to the server!",
      "player.authorize_vote": "Sorry. You need to authorize us on Facebook to vote!",
      "player.incentivized_text": "Consumer received a reward for this video.",

      "player.mansguide.wall": "Wall",
      "player.mansguide.check_out": "Check out the gallery and",
      "player.mansguide.record_your_own_link": "record your own",
      "player.mansguide.record_your_own_header": "Record your own",
      "player.mansguide.video_gallery": "Video gallery",
      "player.mansguide.all_videos": "All videos",
      "player.mansguide.flag_confirm": "Are you sure you want to flag this video?",
      "player.mansguide.no_videos": "Video player goes here. You currently have no videos; please record one!",
      "player.mansguide.vote": "vote",
      "player.mansguide.votes": "votes",
      "player.mansguide.category": "Category",
      "player.mansguide.order": "Sort",
      "player.mansguide.order.star": "Engagement ordering",
      "player.mansguide.order.popularity": "Most popular",
      "player.mansguide.order.approval": "Most recent",
      "player.mansguide.order.views": "Most viewed",
      "player.mansguide.order.rating": "Highest rated",
      "player.mansguide.order.likes": "Most liked",
      "player.mansguide.order.votes": "Most votes",

      "player.mansguide.friends_videos": "Friends' videos",
      "player.mansguide.featured_videos": "Featured videos",
      "player.mansguide.all": "all",
      "player.mansguide.more": "More",
      "player.mansguide.page_number": "page {pageNumber}",
      "player.mansguide.loading_more": "Loading",

      "powered_by": "Powered by VideoGenie",

      "record.help": "Help",
      "record.to_start": "To start recording, just click \"Rec\"!",
      "record.stop": "Stop",
      "record.re_rec": "Re-Rec",
      "record.playback.stop": "Stop",
      "record.playback.play": "Play",
      "record.blinker.recording": "Recording",
      "record.blinker.processing": "Processing",
      "record.blinker.buffering": "Buffering",
      "record.try_again": "We're sorry! You'll need to record your video again.\n\nThis was most likely caused by low audio levels during recording. Please try adjusting your microphone or speaking louder.",
      "record.seeyourself": "If you don't see yourself here, you'll need to select a different webcam from the dropdown menu above.\n\nOtherwise, click \"help\" in the top-right corner.",
      "record.if_happy": "If you're happy with your video, hit \"Next\" to go to the final step.",
      "record.welcome": "Recording your video is as easy as\n1-2-3.",
      "record.instructions": "1. Click \"Allow\" to activate your webcam\n2. Record and review your video\n3. Submit your video",
      "record.lets_get_started": "Let's get started.",
      "record.record_label": "Rec",
      "record.play_label": "Play",
      "record.next_label": "Next",
      "record.error_label": "Error",
      "record.no_camera": "We are unable to start recording a video because access to your camera is denied.  Please allow Flash Player access to your camera.",
      "record.upload_video": "Upload a video instead",
      "record.upload.reload_page": "",
      "record.upload.no_camera": "<p>Missing a webcam? No problem...</p>",
      "record.upload.no_flash": "<p>Download <a href=\"http://get.adobe.com/flashplayer/\" target=\"_blank\">Adobe Flash</a> to record or ...</p>",
      "record.upload.or_upload_file": "<p>Upload a video below or email it to <a href=\"mailto:videos@videogenie.com\">videos@videogenie.com</a> ({duration} Max)</p>",
      "record.upload.choosefile": "Choose File",
      "record.upload.mobilerecord": "Record",
      "record.upload.submit_upload": "Upload",
      "record.upload.submit_btn" : "Submit",
      "record.upload.submit_youtube": "Submit",
      "record.upload.youtube_link_label": "YouTube Video Embed Code or URL",
      "record.upload.youtube_directions": "Copy and paste the embed code or URL for the YouTube video that you would like to add. Then click Submit.",

      "record.help.title": "Need Help?",
      "record.help.dek": "If you need some help or are having technical dificulties please take a second to fill out this form and someone will get back to you.",
      "record.help.name": "Full name *",
      "record.help.email": "Email *",
      "record.help.problem": "Brief description of the problem *",
      "record.help.submit": "Submit",
      "record.help.error": "Please correct the above errors and resubmit",
      "record.help.submit.title": "Help Form Submitted",
      "record.help.submit.dek": "The help form has been submitted. Someone will be in contact with you shortly to resolve this issue. If you have further questions or need more information, please email support@videogenie.com. Thank you for your understanding."
  },

  "de": {
      "record.contrib.info_text": "Keine Sorge, wir sind keine großen Fans von Spam mit. Diese Information ist, damit wir Sie benachrichtigen, wenn Ihr Video auf dem Display benötigt. Wir werden es nicht für andere Zwecke.",
      "record.contrib.or": "oder",
      "record.contrib.first_name": "Vorname:",
      "record.contrib.last_name": "Nachname:",
      "record.contrib.gender":"Geschlecht:",
      "record.contrib.gender_m":"Männlich",
      "record.contrib.gender_f":"Weiblich",
      "record.contrib.birthday":"Geburtstag:",
      "record.contrib.birthdate":"Geburtstag:",
      "record.contrib.birth_year": "Geburtsjahr:",
      "record.contrib.country":"Land:",
      "record.contrib.state":"Wohnort:",
      "record.contrib.zip_code":"Postleitzahl:",
      "record.contrib.email":"Email:",
      "record.contrib.by_clicking_1":"Durch das Absenden Ihrer Angaben erklären Sie sich mit den",
      "record.contrib.by_clicking_2": "von VideoGenie einverstanden!",
      "record.contrib.tos":"ABG's",
      "record.contrib.i_accept":"Absenden",
      "record.success.thankyou":"Vielen Dank für Dein Video!",
      "record.success.we_ll_review":"Wir werden Ihr Video kurz schreiben, und Sie wissen lassen, sobald Ihr Video genehmigt ist.",

      "record.help": "Hilfe"
  },

  "es": {
      "record.contrib.info_text": "Indícanos tus datos para avisarte cuando tu vídeo esté activo. No te preocupes por el spam, esta información no será utilizada para ningún otro propósito.",
      "record.contrib.or": "o",
      "record.contrib.first_name":"Nombre:",
      "record.contrib.last_name":"Apellido:",
      "record.contrib.gender":"Sexo:",
      "record.contrib.gender_m":"Hombre",
      "record.contrib.gender_f":"Mujer",
      "record.contrib.birthday":"Cumpleaños:",
      "record.contrib.birthdate":"Cumpleaños:",
      "record.contrib.birth_year":"Año de nacimiento:",
      "record.contrib.country":"Vivo en:",
      "record.contrib.state":"Estado:",
      "record.contrib.zip_code":"Código postal:",
      "record.contrib.email":"Email:",
      "record.contrib.by_clicking_1":"Al seleccionar esta casilla acepto los",
      "record.contrib.tos":"Términos de servicio y la política de privacidad",
      "record.contrib.by_clicking_2":"de VideoGenie asociados al vídeo.",
      "record.contrib.i_accept":"Enviar vídeo",
      "record.success.thankyou":"¡Gracias!",
      "record.success.we_ll_review":"Revisaremos tu vídeo lo antes posible y te avisaremos cuando tu vídeo sea aprobado.",
      "record.fbshare.meantime": "Mientras tanto, ¡puedes compartir tu vídeo con tus amigos!",

      "redirect.on": "en",
      "redirect.facebook.campaign.description": "VideoGenie Video",

      "player.loading": "Cargando",
      "player.you_need_flash": "Necesita Flash para ver los videos.",
      "player.no_videos": "No hay ningún vídeo todavía.",
      "player.already_voted": "Oops, parece que ya votaste hoy, por favor vuelve mañana y vota de nuevo",
      "player.problem_voting": "Lo siento. Hubo un problema al enviar su voto para el servidor!",
      "player.authorize_vote": "Lo siento. Es necesario que nos autorice en Facebook votar!",

      "player.mansguide.wall": "Wall",
      "player.mansguide.check_out": "Echa un vistazo a la galería y",
      "player.mansguide.record_your_own_link": "grabar su propio",
      "player.mansguide.record_your_own_header": "Grabar su propio",
      "player.mansguide.video_gallery": "Galeria de videos",
      "player.mansguide.all_videos": "Todos los videos",
      "player.mansguide.flag_confirm": "¿Está seguro que desea marcar este video?",
      "player.mansguide.vote": "voto",
      "player.mansguide.votes": "votos",
      "player.mansguide.category": "Categoría",
      "player.mansguide.order": "Orden",
      "player.mansguide.order.star": "Sin orden ni concierto",
      "player.mansguide.order.popularity": "Lo más leído",
      "player.mansguide.order.approval": "Los más recientes",
      "player.mansguide.order.views": "Los más vistos",
      "player.mansguide.order.rating": "Los más altos clasificado",
      "player.mansguide.order.likes": "Los más querido",
      "player.mansguide.order.votes": "Los que tienen la mayoría de los votos",
      "player.mansguide.friends_videos": "Videos de amigos",
      "player.mansguide.featured_videos": "Videos destacados",
      "player.mansguide.all": "Todos",
      "player.mansguide.more": "Mas",
      "player.mansguide.loading_more": "Cargando",

      "powered_by": "Desarrollado por VideoGenie",

      "record.help": "Ayuda",
      "record.to_start": "Para iniciar la grabación, ¡pulsa sobre \"Grabar\"!",
      "record.stop": "Parar",
      "record.re_rec": "Re-grabar",
      "record.playback.stop": "Parar",
      "record.playback.play": "Reproducir",
      "record.blinker.recording": "Grabando",
      "record.blinker.processing": "Procesando",
      "record.blinker.buffering": "Búfer",
      "record.try_again": "Ha ocurrido un error al procesar tu vídeo. Posiblemente ha sido un problema de sonido. Por favor, ajusta tu micrófono e inténtalo de nuevo.",
      "record.seeyourself": "Si no puedes verte, tendrás que elegir otra webcam en el menú desplegable de arriba.",
      "record.if_happy": "Si estás contento con tu vídeo, pulsa sobre \"Siguiente\" para pasar al último paso.",
      "record.welcome": "¡Bienvenido! Grabar tu vídeo es muy simple, son solo 3 pasos.",
      "record.instructions": "1. Pulsa sobre \"Aceptar\" para activar tu cámara\n2. Graba y revisa tu vídeo\n3. Envía tu vídeo",
      "record.lets_get_started": "¡Comencemos!",
      "record.record_label": "Grabar",
      "record.play_label": "Reproducir",
      "record.next_label": "Siguiente",
      "record.error_label": "Error",
      "record.no_camera": "No puedes empezar a grabar porque se ha denegado el acceso a tu cámara, por favor, permite a Flash Player acceder a tu cámara.",

      "record.help.title": "¿Necesitas ayuda?",
      "record.help.dek": "Si has tenido dificultades para participar, solo escribe tus datos y en las próximas horas te contactaremos.",
      "record.help.name": "Nombre completo *",
      "record.help.email": "Correo electrónico *",
      "record.help.problem": "Breve descripción del problema *",
      "record.help.submit": "Enviar",
      "record.help.error": "Por favor corrige los errores y vuelve a intentar",
      "record.help.submit.title": "Ayuda Formulario Enviado",
      "record.help.submit.dek": "La forma de ayuda ha sido enviada. Alguien se pondrá en contacto con usted en breve para resolver este problema. Si tiene alguna duda o necesita más información, por favor support@videogenie.com correo electrónico. Gracias por su comprensión."
  },

  "es-AR": {
      "record.contrib.info_text": "Déjanos tus datos para avisarte cuando tu video esté activo. Esta información no será utilizada para ningún otro propósito.",
      "record.contrib.or": "o",
      "record.contrib.first_name":"Nombre:",
      "record.contrib.last_name":"Apellido:",
      "record.contrib.gender":"Sexo:",
      "record.contrib.gender_m":"Hombre",
      "record.contrib.gender_f":"Mujer",
      "record.contrib.birthday":"Cumpleaños:",
      "record.contrib.birthdate":"Cumpleaños:",
      "record.contrib.birth_year":"Año de nacimiento:",
      "record.contrib.country":"Vivo en:",
      "record.contrib.state":"Estado:",
      "record.contrib.zip_code":"Código postal:",
      "record.contrib.email":"Email:",
      "record.contrib.by_clicking_1":"Al seleccionar esta casilla acepto los",
      "record.contrib.tos":"Términos de servicio y la política de privacidad",
      "record.contrib.by_clicking_2":"de VideoGenie asociados al vídeo.",
      "record.contrib.i_accept":"Enviar video",
      "record.success.thankyou":"¡Chévere! ¡Gracias por participar!",
      "record.success.we_ll_review":"Revisaremos tu video a la brevedad y te estaremos avisando cuando tu video sea aprobado.",
      "record.fbshare.meantime": "Mientras tanto, ¡podés compartir tu video con tus amigos!",

      "redirect.on": "en",
      "redirect.facebook.campaign.description": "VideoGenie Video",

      "player.loading": "Cargando",
      "player.you_need_flash": "Necesita Flash para ver los videos.",
      "player.no_videos": "No hay ningún vídeo todavía.",
      "player.already_voted": "Oops, parece que ya votaste hoy, por favor vuelve mañana y vota de nuevo",
      "player.problem_voting": "Lo siento. Hubo un problema al enviar su voto para el servidor!",
      "player.authorize_vote": "Lo siento. Es necesario que nos autorice en Facebook votar!",

      "player.mansguide.wall": "Wall",
      "player.mansguide.check_out": "Echa un vistazo a la galería y",
      "player.mansguide.record_your_own_link": "grabar su propio",
      "player.mansguide.record_your_own_header": "Grabar su propio",
      "player.mansguide.video_gallery": "Galeria de videos",
      "player.mansguide.all_videos": "Todos los videos",
      "player.mansguide.flag_confirm": "¿Está seguro que desea marcar este video?",
      "player.mansguide.vote": "voto",
      "player.mansguide.votes": "votos",
      "player.mansguide.category": "Categoría",
      "player.mansguide.order": "Orden",
      "player.mansguide.order.star": "Sin orden ni concierto",
      "player.mansguide.order.popularity": "Lo más leído",
      "player.mansguide.order.approval": "Los más recientes",
      "player.mansguide.order.views": "Los más vistos",
      "player.mansguide.order.rating": "Los más altos clasificado",
      "player.mansguide.order.likes": "Los más querido",
      "player.mansguide.order.votes": "Los que tienen la mayoría de los votos",
      "player.mansguide.friends_videos": "Videos de amigos",
      "player.mansguide.featured_videos": "Videos destacadoS",
      "player.mansguide.all": "todos",
      "player.mansguide.more": "Mas",
      "player.mansguide.loading_more": "Cargando",

      "powered_by": "Desarrollado por VideoGenie",

      "record.help": "Ayuda",
      "record.to_start": "Para iniciar la grabación, ¡haga clic en \"Grabar\"!",
      "record.stop": "Parar",
      "record.re_rec": "Re-grabar",
      "record.playback.stop": "Parar",
      "record.playback.play": "Revisar",
      "record.blinker.recording": "Grabando",
      "record.blinker.processing": "Procesando",
      "record.blinker.buffering": "Búfer",
      "record.try_again": "Ha ocurrido un error al procesar tu video. Posiblemente ha sido un problema de sonido. Por favor, tratá ajustando tu micrófono y probá de nuevo.",
      "record.seeyourself": "Si no te ves aquí, tendrás que elegir otra webcam en el menú desplegable de arriba.",
      "record.if_happy": "Si estás contento con tu video, clickeá en \"Siguiente\" para pasar al último paso.",
      "record.welcome": "¡Bienvenido! Grabar tu video es muy simple, son sólo 3 pasos.",
      "record.instructions": "1. Clickeá en \"Aceptar\" para activar tu cámara\n2. Grabá y revisá tu video\n3. Enviá tu video",
      "record.lets_get_started": "¡Comencemos!",
      "record.record_label": "Grabar",
      "record.play_label": "Revisar",
      "record.next_label": "Siguiente",
      "record.error_label": "Error",
      "record.no_camera": "No podés empezar a grabar porque el acceso a tu cámara ha sido denegado, por favor aceptá que Flash Player acceda a tu cámara."

  },

  "pt": {
      "record.contrib.info_text": "Informe os seus dados para que possamos avisá-lo quando seu vídeo estiver ativo. Essas informações não serão utilizadas para nenhum outro propósito.",
      "record.contrib.or": "ou",
      "record.contrib.first_name": "Nome:",
      "record.contrib.last_name": "Apelido:",
      "record.contrib.gender": "Sexo:",
      "record.contrib.gender_m": "M",
      "record.contrib.gender_f": "F",
      "record.contrib.birth_year": "Ano de nascimento:",
      "record.contrib.email": "E-mail:",
      "record.contrib.by_clicking_1": "Ao clicar nesta caixa, concordo com os",
      "record.contrib.tos": "Termos de serviço e com a política de privacidade",
      "record.contrib.by_clicking_2": "de VideoGenie associados ao vídeo.",
      "record.contrib.i_accept": "Enviar um vídeo",
      "record.success.thankyou": "Obrigado!",
      "record.success.we_ll_review": "Iremos analisar o seu vídeo em breve e informá-lo assim que o mesmo for aprovado.",
      "record.fbshare.meantime": "Entretanto, pode partilhar o vídeo com os seus amigos!",

      "redirect.on": "no",
      "redirect.facebook.campaign.description": "Vídeo VideoGenie",

      "player.loading": "Carregando",
      "player.you_need_flash": "Você precisa do Flash para ver os vídeos.",
      "player.no_videos": "Não há vídeos ainda.",

      "player.mansguide.wall": "Wall",
      "player.mansguide.check_out": "Confira a galeria e",
      "player.mansguide.record_your_own_link": "gravar os seus próprios",
      "player.mansguide.record_your_own_header": "Gravar os seus proprios",
      "player.mansguide.video_gallery": "Galeria de videos",
      "player.mansguide.all_videos": "Todos os videos",
      "player.mansguide.flag_confirm": "Tem certeza de que deseja sinalizar este vídeo?",
      "player.mansguide.vote": "voto",
      "player.mansguide.votes": "votos",
      "player.mansguide.category": "Categoria",
      "player.mansguide.order": "Ordem",
      "player.mansguide.order.star": "Acaso",
      "player.mansguide.order.popularity": "Populares",
      "player.mansguide.order.approval": "As mais recente",
      "player.mansguide.order.views": "Os mais vistos",
      "player.mansguide.order.rating": "Os de maior audiência",
      "player.mansguide.order.likes": "As mais-gostado",
      "player.mansguide.order.votes": "Com mais votos",
      "player.mansguide.friends_videos": "Videos dos amigos",
      "player.mansguide.featured_videos": "Videos em destaque",
      "player.mansguide.all": "todos",
      "player.mansguide.more": "Mais",
      "player.mansguide.loading_more": "Carregando",

      "powered_by": "Alimentado por VideoGenie",

      "record.help": "Ajuda",
      "record.to_start": "Para começar a gravar, basta clicar em \"Gravar\"!",
      "record.stop": "Parar",
      "record.re_rec": "Regravar",
      "record.playback.stop": "Parar",
      "record.playback.play": "Reproduzir",
      "record.blinker.recording": "A gravar",
      "record.blinker.processing": "A processar",
      "record.blinker.buffering": "Buffering",
      "record.try_again": "Lamentamos, mas necessita de gravar novamente o vídeo. Isto provavelmente deve-se aos baixos níveis de áudio durante a gravação. Experimente ajustar o microfone ou falar mais alto.",
      "record.seeyourself": "Se não se visualiza, necessita de seleccionar uma câmara Web diferente no menu pendente supracitado.",
      "record.if_happy": "Se está satisfeito com o vídeo, clique em \"Seguinte\" para avançar para o último passo.",
      "record.welcome": "¡Bem-vindo! Gravar o seu vídeo é tão fácil como contar até três.",
      "record.instructions": "1. Clique em \"Permitir\" para activar a câmara Web\n2. Grave e visualize o vídeo\n3. Envie o vídeo",
      "record.lets_get_started": "Vamos começar!",
      "record.record_label": "Gravar",
      "record.play_label": "Reproduzir",
      "record.next_label": "Seguinte",
      "record.error_label": "Erro",
      "record.no_camera": "Não é possível gravar um vídeo, pois o acesso à câmara é negado. Permita que o Flash Player aceda à câmara."
  },

  "pt-BR": {
      "record.contrib.info_text": "Informe os seus dados para que possamos avisá-lo quando seu vídeo estiver ativo. Essas informações não serão utilizadas para nenhum outro propósito.",
      "record.contrib.or": "ou",
      "record.contrib.first_name": "Nome:",
      "record.contrib.last_name": "Sobrenome:",
      "record.contrib.gender": "Sexo:",
      "record.contrib.gender_m": "M",
      "record.contrib.gender_f": "F",
      "record.contrib.birth_year": "Ano de nascimento:",
      "record.contrib.email": "E-mail:",
      "record.contrib.by_clicking_1": "Ao clicar nesta caixa, eu concordo com os",
      "record.contrib.tos": "Termos de serviço e política de privacidade",
      "record.contrib.by_clicking_2": "associados ao envio de meu vídeo.",
      "record.contrib.i_accept": "Enviar vídeo",
      "record.success.thankyou": "Obrigado!",
      "record.success.we_ll_review": "Nós analisaremos seu vídeo em breve, e o informaremos assim que seu vídeo for aprovado.",
      "record.fbshare.meantime": "Enquanto isto, Você poderá compartir seu vídeo com seus amigos!",

      "redirect.on": "no",
      "redirect.facebook.campaign.description": "Vídeo VideoGenie",

      "player.loading": "Carregando",
      "player.you_need_flash": "Você precisa do Flash para ver os vídeos.",
      "player.no_videos": "Não há vídeos ainda.",

      "player.mansguide.wall": "Wall",
      "player.mansguide.check_out": "Confira a galeria e",
      "player.mansguide.record_your_own_link": "gravar os seus próprios",
      "player.mansguide.record_your_own_header": "Gravar os seus proprios",
      "player.mansguide.video_gallery": "Galeria de videos",
      "player.mansguide.all_videos": "Todos os videos",
      "player.mansguide.flag_confirm": "Tem certeza de que deseja sinalizar este vídeo?",
      "player.mansguide.vote": "voto",
      "player.mansguide.votes": "votos",
      "player.mansguide.category": "Categoria",
      "player.mansguide.order": "Ordem",
      "player.mansguide.order.star": "Acaso",
      "player.mansguide.order.popularity": "Populares",
      "player.mansguide.order.approval": "As mais recente",
      "player.mansguide.order.views": "Os mais vistos",
      "player.mansguide.order.rating": "Os de maior audiência",
      "player.mansguide.order.likes": "As mais-gostado",
      "player.mansguide.order.votes": "Com mais votos",
      "player.mansguide.friends_videos": "Videos dos amigos",
      "player.mansguide.featured_videos": "Videos em destaque",
      "player.mansguide.all": "todos",
      "player.mansguide.more": "Mais",
      "player.mansguide.loading_more": "Carregando",

      "powered_by": "Alimentado por VideoGenie",

      "record.help": "Ajuda",
      "record.to_start": "Para começar a gravar, basta clicar em \"Gravar\"!",
      "record.stop": "Parar",
      "record.re_rec": "Re-gravar",
      "record.playback.stop": "Parar",
      "record.playback.play": "Revisar",
      "record.blinker.recording": "Gravando",
      "record.blinker.processing": "Processando",
      "record.blinker.buffering": "Buffering",
      "record.try_again": "Ocorreu um erro durante o processamento de seu vídeo.\n\nProvavelmente, foi um problema com os baixos níveis de áudio. Ajuste seu microfone ou fale mais alto, e tente novamente.",
      "record.seeyourself": "Se você não se vir aqui, você precisará selecionar uma webcam diferente a partir do menu acima.",
      "record.if_happy": "Se estiver satisfeito com o vídeo, clique em \"Avançar\" para ir à etapa final.",
      "record.welcome": "Bem-vindo! Gravar o seu vídeo é muito fácil. São só três passos:",
      "record.instructions": "1. Clique em 'Permitir' para ativar sua webcam\n2. Grave e revise seu vídeo\n3. Envie seu vídeo",
      "record.lets_get_started": "Vamos começar!",
      "record.record_label": "Gravar",
      "record.play_label": "Revisar",
      "record.next_label": "Avançar",
      "record.error_label": "Erro",
      "record.no_camera": "Você  não pode começar a gravar o seu vídeo, pois o acesso à sua câmera foi negado. Por favor, permita o acesso do Flash Player para poder usar a câmera."
  },

  "fr": {
      "record.help": "Aide",
      "record.blinker.processing": "En traitement",
      "record.contrib.country": "Pays :",
      "record.try_again": "Désolé ! Vous devez enregistrer votre vidéo à nouveau. Probablement à cause du niveau audio trop bas durant l'enregistrement. Essayez d'ajuster votre micro ou de parler plus fort.",
      "record.instructions": "1. Cliquez \"Allow\" pour activer votre webcaméra. \n2.  Enregistrez et revoyez votre vidéo. \n3. Soumettez votre vidéo",
      "record.contrib.i_accept": "Soumettre une vidéo",
      "record.play_label": "Jouer",
      "player.mansguide.video_gallery": "Gallerie vidéo",
      "record.vidinfo.video_title": "Titre de la vidéo :",
      "record.success.thankyou": "Merci !",
      "record.welcome": "Enregistrer une vidéo est un jeu d'enfant.",
      "record.next_label": "Suivant",
      "record.no_camera": "Nous ne pouvons commencer l'enregistrement puisque l'accès à votre caméra a été refusé. Veuillez permettre à Flash Player d'accéder à votre caméra.",
      "record.success.we_ll_review": "Nous regarderons votre vidéo sous peu et vous ferons savoir dès qu'elle sera approuvée.",
      "record.stop": "Arrêt",
      "record.fbshare.record_your_own": "Enregistrez la vôtre",
      "player.mansguide.all": "tous",
      "record.blinker.buffering": "Mise en mémoire-tampon",
      "player.mansguide.check_out": "Consultez la galerie et ",
      "record.error_label": "Erreur",
      "record.contrib.first_name": "Prénom :",
      "player.mansguide.more": "Plus",
      "player.mansguide.page_number": "page {pageNumber}",
      "record.blinker.recording": "Enregistre",
      "player.you_need_flash": "Vous devez avoir installé Flash pour pouvoir voir ces vidéos.",
      "record.contrib.or": "ou",
      "player.mansguide.record_your_own_link": "enregistrez la vôtre",
      "record.contrib.please_login": "Veuillez ouvrir une session via Facebook.",
      "record.contrib.gender_m": "H",
      "record.contrib.by_clicking_1": "En cochant cette case, je consens aux",
      "record.contrib.tos": "Termes de services et politique de confidentialité",
      "record.contrib.by_clicking_2": "de VideoGenie associés a la soumission de ma video.",
      "player.no_videos": "Il n'y a pas encore de vidéos",
      "player.mansguide.record_your_own_header": "Enregistrez la vôtre",
      "record.contrib.zip_code": "Code postal :",
      "record.record_label": "Enregistrer",
      "record.contrib.birthday": "Anniversaire :",
      "record.contrib.birthdate": "Date de naissance :",
      "record.contrib.birth_year": "Année de naissance:",
      "player.mansguide.all_videos": "Toutes les vidéos",
      "player.mansguide.flag_confirm": "Etes-vous sûr de vouloir signaler cette vidéo?",
      "player.mansguide.vote": "vote",
      "player.mansguide.votes": "votes",
      "player.mansguide.category": "Categorie",
      "player.mansguide.order": "Ordre",
      "player.mansguide.order.star": "Aléatoire",
      "player.mansguide.order.popularity": "Les plus populaires",
      "player.mansguide.order.approval": "Les plus récentes",
      "player.mansguide.order.views": "Les mieux visionnées",
      "player.mansguide.order.rating": "Les mieux notées",
      "player.mansguide.order.likes": "Les mieux aimées",
      "player.mansguide.order.votes": "Les plus votées",
      "player.mansguide.friends_videos": "Vidéos d'amis",
      "player.loading": "Chargement",
      "record.if_happy": "Si vous êtes satisfait, cliquez \"Suivant\" pour vous rendre à l'étape finale.",
      "player.mansguide.featured_videos": "Vidéos En Vedette",
      "record.contrib.info_text": "Ne vous inquiétez pas, nous n'aimons pas les pourriels non plus. Cette info nous servira à vous avertir quand votre vidéo sera à l'affiche. Nous ne l'utiliserons pour aucune autre raison.",
      "record.vidinfo.tag_a_friend": "Identifiez un ami :",
      "record.re_rec": "Réenreg",
      "record.contrib.gender_f": "F",
      "powered_by": "Propulsé par VideoGenie",
      "record.playback.play": "Jouer",
      "record.to_start": "Pour commencer, cliquez sur \"Enregistrer\".",
      "player.mansguide.loading_more": "Chargement",
      "record.contrib.email": "Courriel :",
      "redirect.facebook.campaign.description": "Vidéo de VideoGenie",
      "record.contrib.last_name": "Nom de famille :",
      "record.fbshare.meantime": "En attendant, vous pouvez partager vos vidéos avec vos amis !",
      "record.seeyourself": "Si vous ne vous voyez pas ici, choisissez une caméra différente dan le menu ci-dessus. Sinon, cliquez sur Aide dans le coin droit en haut.",
      "record.contrib.state": "Province :",
      "player.no_videos_in_cat": "Il n'y a pas de vidéo dans cette catégorie.",
      "redirect.on": "sur",
      "record.contrib.birth_year": " Année de naissance :",
      "record.lets_get_started": "C'est parti.",
      "record.playback.stop": "Arrêter",
      "record.contrib.gender": "Sexe :",
      "player.mansguide.wall": "Mur",
      "record.vidinfo.category": "Catégorie :",
      "record.upload_video": "Télécharger une vidéo à la place"
  },

  "fr-CA": {
      "record.help": "Aide",
      "record.blinker.processing": "En traitement",
      "record.contrib.country": "Pays :",
      "record.try_again": "Désolé ! Vous devez enregistrer votre vidéo à nouveau. Probablement à cause du niveau audio trop bas durant l'enregistrement. Essayez d'ajuster votre micro ou de parler plus fort.",
      "record.instructions": "1. Cliquez \"Allow\" pour activer votre webcaméra. \n2.  Enregistrez et voyez votre vidéo. \n3. Soumettez votre vidéo",
      "record.contrib.i_accept": "Soumettre une vidéo",
      "record.play_label": "Jouer",
      "player.mansguide.video_gallery": "Gallerie vidéo",
      "record.vidinfo.video_title": "Titre de la vidéo :",
      "record.success.thankyou": "Merci !",
      "record.welcome": "Enregistrer une vidéo est un jeu d'enfant.",
      "record.next_label": "Suivant",
      "record.no_camera": "Nous ne pouvons commencer l'enregistrement puisque l'accès à votre caméra a été refusé. Veuillez permettre à Flash Player d'accéder à votre caméra.",
      "record.success.we_ll_review": "Nous regarderons votre vidéo sous peu et vous laisserons savoir dès qu'elle sera approuvée.",
      "record.stop": "Arrêt",
      "record.fbshare.record_your_own": "Enregistrez la vôtre",
      "player.mansguide.all": "tous",
      "record.blinker.buffering": "Mise en mémoire-tampon",
      "player.mansguide.check_out": "Consultez la galerie et ",
      "record.error_label": "Erreur",
      "record.contrib.first_name": "Prénom :",
      "player.mansguide.more": "Plus",
      "player.mansguide.page_number": "page {pageNumber}",
      "record.blinker.recording": "Enregistre",
      "player.you_need_flash": "Vous devez avoir installé Flash pour pouvoir voir ces vidéos.",
      "record.contrib.or": "ou",
      "player.mansguide.record_your_own_link": "enregistrez la vôtre",
      "record.contrib.please_login": "Veuillez ouvrir une session via Facebook.",
      "record.contrib.gender_m": "H",
      "record.contrib.by_clicking_1": "En cochant cette case, je consens aux",
      "record.contrib.tos": "Termes de services et politique de confidentialité",
      "record.contrib.by_clicking_2": "de VideoGenie associés a la soumission de ma video.",
      "player.no_videos": "Il n'y a pas encore de vidéos",
      "player.mansguide.record_your_own_header": "Enregistrez la vôtre",
      "record.contrib.zip_code": "Code postal :",
      "record.record_label": "Enregistrer",
      "record.contrib.birthday": "Anniversaire :",
      "record.contrib.birthdate": "Date de naissance :",
      "record.contrib.birth_year": "Année de naissance:",
      "player.mansguide.all_videos": "Toutes les vidéos",
      "player.mansguide.flag_confirm": "Etes-vous sûr de vouloir signaler cette vidéo?",
      "player.mansguide.vote": "vote",
      "player.mansguide.votes": "votes",
      "player.mansguide.category": "Categorie",
      "player.mansguide.order": "Ordre",
      "player.mansguide.order.star": "Aléatoire",
      "player.mansguide.order.popularity": "Les plus populaires",
      "player.mansguide.order.approval": "Les plus récentes",
      "player.mansguide.order.views": "Les mieux visionnées",
      "player.mansguide.order.rating": "Les mieux notées",
      "player.mansguide.order.likes": "Les mieux aimées",
      "player.mansguide.order.votes": "Les plus votées",
      "player.mansguide.friends_videos": "Vidéos D'Amis",
      "player.loading": "Chargement",
      "record.if_happy": "Si vous êtes satisfait, cliquez \"Suivant\" pour vous rendre à l'étape finale.",
      "player.mansguide.featured_videos": "Vidéos En Vedette",
      "record.contrib.info_text": "Ne vous inquiétez pas, nous n'aimons pas les pourriels non plus. Cette info nous servira à vous avertir quand votre vidéo sera à l'affiche. Nous ne l'utiliserons pour aucune autre raison.",
      "record.vidinfo.tag_a_friend": "Identifiez un ami :",
      "record.re_rec": "Réenreg",
      "record.contrib.gender_f": "F",
      "powered_by": "Propulsé par VideoGenie",
      "record.playback.play": "Jouer",
      "record.to_start": "Pour commencer, cliquez sur \"Enregistrer\".",
      "player.mansguide.loading_more": "Chargement",
      "record.contrib.email": "Courriel :",
      "redirect.facebook.campaign.description": "Vidéo de VideoGenie",
      "record.contrib.last_name": "Nom de famille :",
      "record.fbshare.meantime": "En attendant, vous pouvez partager vos vidéos avec vos amis !",
      "record.seeyourself": "Si vous ne vous voyez pas ici, choisissez une caméra différente dan le menu ci-dessus. Sinon, cliquez sur Aide dans le coin droit en haut.",
      "record.contrib.state": "Province :",
      "player.no_videos_in_cat": "Il n'y a pas de vidéo dans cette catégorie.",
      "redirect.on": "sur",
      "record.contrib.birth_year": " Année de naissance :",
      "record.lets_get_started": "C'est parti.",
      "record.playback.stop": "Arrêter",
      "record.contrib.gender": "Sexe :",
      "player.mansguide.wall": "Mur",
      "record.vidinfo.category": "Catégorie :",
      "record.upload_video": "Télécharger une vidéo à la place"
  },

  "tr": {
      "record.help": "Yardım",
      "record.blinker.processing": "İşleniyor",
      "record.contrib.country": "Ülke:",
      "record.try_again": "Üzgünüz. Video'nun tekrar kaydedilmesi gerekmekte. Bu durum muhtemelen mikrofonunun ses seviyesinin düşük kalmasından kaynaklanıyor. Lütfen daha yüksek bir ses seviyesiyle tekrar dene.",
      "record.instructions": "1. \"İzin Ver\" tuşuna tıklayarak kameranı aktive et.\n2. Video'nu kaydet.\n3. Video'nu Onayla ve Gönder.",
      "record.contrib.i_accept": "Video'yu Onayla.",
      "record.play_label": "Oynat",
      "player.mansguide.video_gallery": "TÜM VİDEOLAR",
      "record.vidinfo.video_title": "Video Başlığı:",
      "record.success.thankyou": "Teşekkürler!",
      "record.welcome": "Kendi Video'nu kaydetmek çok kolay.",
      "record.next_label": "Devam Et",
      "record.no_camera": "Kayıta başlayamıyoruz, çünkü web kamerana erişim engelleniyor. Lütfen Flash Oynatıcısının kamerana ulaşmasına izin verin.",
      "record.success.we_ll_review": "Video kontrol edilip onaylandıktan kısa bir süre sonra tarafına email yoluyla bilgilendirme yapılacaktır.",
      "record.stop": "Durdur",
      "record.fbshare.record_your_own": "Kendi video'nu kaydet.",
      "player.mansguide.all": "Tümü",
      "record.blinker.buffering": "Ön belleğe alınıyor",
      "player.mansguide.check_out": "Video'lara göz at ve",
      "record.error_label": "Hata",
      "record.contrib.first_name": "İsim:",
      "player.mansguide.more": "DAHA FAZLA",
      "record.blinker.recording": "Kayıtta",
      "player.you_need_flash": "Videoları izlemek için bilgisayarda Flash yüklü olması gerekmektedir.",
      "record.contrib.or": "veya",
      "player.mansguide.record_your_own_link": "kendi videonu kaydet",
      "record.contrib.please_login": "Facebook ile Giriş Yap.",
      "record.contrib.gender_m": "Erkek",
      "record.contrib.by_clicking_1": "Eklemiş olduğum",
      "record.contrib.tos": "video ile ilgili",
      "record.contrib.by_clicking_2": "servis koşullarını kabul ediyorum.",
      "player.no_videos": "Henüz herhangi bir video bulunmamakta.",
      "player.mansguide.record_your_own_header": "Kendi videonu kaydet",
      "record.contrib.zip_code": "Posta Kodu:",
      "record.record_label": "Kayda Başla",
      "record.contrib.birthday": "Doğum Tarihin:",
      "record.contrib.birthdate": "Doğum Tarihin:",
      "player.mansguide.all_videos": "Tüm videolar",
      "player.mansguide.flag_confirm": "Bu videoyu bayrak istediğiniz emin misiniz?",
      "player.mansguide.vote": "oy",
      "player.mansguide.votes": "oy",
      "player.mansguide.category": "Kategori",
      "player.mansguide.order": "Sipariş",
      "player.mansguide.order.star": "Rasgele",
      "player.mansguide.order.popularity": "Varsayılan",
      "player.mansguide.order.approval": "En yakın olanlar",
      "player.mansguide.order.views": "En çok görüntülenen",
      "player.mansguide.order.rating": "En yüksek oranlı olanlar",
      "player.mansguide.order.likes": "En sevdikleriniz",
      "player.mansguide.order.votes": "En çok oy olanlar",
      "player.mansguide.friends_videos": "Arkadaşlarinin videolari",
      "player.loading": "Yükleniyor",
      "record.if_happy": "Eğer videon'dan memnunsan, \"Devam Et\" tuşuna tıklayarak son adıma geçebilirsin.",
      "player.mansguide.featured_videos": "En çok izlenen videolar",
      "record.contrib.info_text": "Ekibimiz, bilgi gizliliğine büyük önem vermektedir. Bilgileriniz, size bu video ile ilgili bilgi vermek dışında kesinlikle kullanılmayacaktır.",
      "record.vidinfo.tag_a_friend": "Arkadaşını Etiketle:",
      "record.re_rec": "Tekrar Kay.",
      "record.contrib.gender_f": "Kadın",
      "powered_by": "VideoGenie alt yapısı kullanılmaktadır.",
      "record.playback.play": "Oynat",
      "record.to_start": "Kayda başlamak için, \"Kayda Başla\" tuşuna tıklaman yeterli.",
      "player.mansguide.loading_more": "Yükleniyor",
      "record.contrib.email": "Email:",
      "redirect.facebook.campaign.description": "VideoGenie Video",
      "record.contrib.last_name": "Soyad:",
      "record.fbshare.meantime": "Beklerken, video'nu arkadaşlarınla paylaşabilirsin!",
      "record.seeyourself": "Eğer kendinizi burada göremiyorsanız, yukarı soldaki menüden başka bir web kamerasını seçmelisiniz. Yine olmuyorsa, yukarıdan \"Yardım\" butonunu tıklayın.",
      "record.contrib.state": "Semt:",
      "player.no_videos_in_cat": "Bu kategoride video bulunmamaktadır.",
      "redirect.on": "Açık",
      "record.contrib.birth_year": "Doğum Yılın:",
      "record.lets_get_started": "Başlayalım.",
      "record.playback.stop": "Durdur",
      "record.contrib.gender": "Cinsiyet:",
      "player.mansguide.wall": "Duvar",
      "record.vidinfo.category": "Kategori:"
  },

  "fi": {
      "player.loading": "Lataa",
      "player.mansguide.all": "kaikki",
      "player.mansguide.all_videos": "Kaikki videot",
      "player.mansguide.category": "",
      "player.mansguide.check_out": "Katso galleria ja ",
      "player.mansguide.featured_videos": "Videonostot",
      "player.mansguide.flag_confirm": "",
      "player.mansguide.friends_videos": "Kavereiden videot",
      "player.mansguide.loading_more": "",
      "player.mansguide.more": "Lisää",
      "player.mansguide.order": "",
      "player.mansguide.order.approval": "",
      "player.mansguide.order.likes": "",
      "player.mansguide.order.rating": "",
      "player.mansguide.order.views": "",
      "player.mansguide.order.votes": "",
      "player.mansguide.record_your_own_header": "Nauhoita omasi",
      "player.mansguide.record_your_own_link": "nauhoita omasi",
      "player.mansguide.video_gallery": "Video galleria",
      "player.mansguide.vote": "",
      "player.mansguide.votes": "",
      "player.mansguide.wall": "Seinä",
      "player.no_videos": "Henüz herhangi bir video bulunmamakta.",
      "player.no_videos_in_cat": "Tässä kategoriassa ei ole videoita",
      "player.no_videos": "Täällä ei ole vielä videoita",
      "player.you_need_flash": "Tarvitset Flash Playerin katsoaksesi videoita",
      "powered_by": "VideoGenie",
      "record.blinker.buffering": "Puskuroi",
      "record.blinker.processing": "Prosessoi",
      "record.blinker.recording": "Nauhoittaa",
      "record.contrib.birthday": "Syntymäpäivä:",
      "record.contrib.birthdate": "Syntymäpäivä:",
      "record.contrib.birth_year": "Syntymävuosi:",
      "record.contrib.by_clicking_1": "Hyväksyn",
      "record.contrib.by_clicking_2": "",
      "record.contrib.country": "Maa:",
      "record.contrib.email": "S-posti:",
      "record.contrib.first_name": "Etunimi:",
      "record.contrib.gender": "Sukupuoli:",
      "record.contrib.gender_f": "F",
      "record.contrib.gender_m": "M",
      "record.contrib.i_accept": "Lähetä video",
      "record.contrib.info_text": "Älä hätäile, emme ole spämmin ystäviä. Tarvitsemme tiedon, jotta voimme ilmoittaa sinulle, kun videosi on katsottavana. Emme käytä tietojasi muihin tarkoituksiin.",
      "record.contrib.last_name": "Sukunimi:",
      "record.contrib.or": "tai",
      "record.contrib.please_login": "Kirjaudu Facebook-tunnuksilla",
      "record.contrib.state": "Maakunta:",
      "record.contrib.tos": "palveluun soveltuvat käyttöehdot",
      "record.contrib.zip_code": "Postinumero:",
      "record.error_label": "Virhe",
      "record.fbshare.meantime": "Sillä välin, voit jakaa videon ystävillesi!",
      "record.fbshare.record_your_own": "Nahoita oma videosi",
      "record.help": "Apua",
      "record.if_happy": "Jos olet tyytyväinen videoosi, paina \"Seuraava\"  ja suorita viimeinen askel.",
      "record.instructions": "1. Klikkaa \"Allow\" aktivoidaksesi webcami\n2. Nauhoita ja katso videosi\n3. Lähetä videosi",
      "record.lets_get_started": "Aloitetaan!",
      "record.next_label": "Seuraava",
      "record.no_camera": "Nahoitus ei käynnistynyt koska emme saaneet yhteyttä webcamiisi. Annathan Flash playerille oikeuden ottaa yhteyden kameraasi",
      "record.playback.play": "Play",
      "record.playback.stop": "Stop",
      "record.play_label": "Play",
      "record.record_label": "Rec",
      "record.re_rec": "Re-rec",
      "record.seeyourself": "Jos et näe itseäsi tässä, vaihda kameraa yllä olevasta alasvetovalikosta.\nMuutoin, klikkaa \"Apua\" oikeasta ylänurkasta.",
      "record.stop": "Stop",
      "record.success.thankyou": "Kiitos!",
      "record.success.we_ll_review": "Tarkistamme videon pian ja ilmoitamme heti, kun se on hyväksytty.",
      "record.to_start": "Klikkaa \"Rec\", kun haluat aloittaa nauhoituksen",
      "record.try_again": "Olemme pahoillamme, sinun täytyy nauhoittaa videosi uudelleen.\nOngelma johtuu luultavasti alhaisesta äänentasosta nauhoituksen aikana. Kokeile mikrofonin säätämistä tai kovempaa puhumista.",
      "record.vidinfo.category": "Kategoria:",
      "record.vidinfo.tag_a_friend": "Taggaa ystäväsi:",
      "record.vidinfo.video_title": "Videon nimi:",
      "record.welcome": "Videon nauhoittaminen on helppoa!\n1-2-3.",
      "redirect.facebook.campaign.description": "VideoGenie Video",
      "redirect.on": "ja"
    },
  "ja": {
      "record.contrib.info_text": "スパム・メールは送信されませんのでご安心ください。この情報は、貴社のビデオが掲載されたことをお知らせするために必要です。その他の目的には使用いたしません。",
      "record.contrib.or": "または",
      "record.contrib.please_login": "Facebookからログインしてください。",
      "record.contrib.first_name": "姓：", "__comment": "it actually means last name: hack to invert the order of display in contributor info",
      "record.contrib.last_name": "名：",
      "record.contrib.gender": "性別：",
      "record.contrib.gender_m": "男性",
      "record.contrib.gender_f": "女性",
      "record.contrib.birthday": "誕生日：",
      "record.contrib.birthdate": "Birth date:",
      "record.contrib.birth_year": "誕生年：",
      "record.contrib.country": "国：",
      "record.contrib.state": "状態：",
      "record.contrib.zip_code": "郵便番号：",
      "record.contrib.email": "e-メール：",
      "record.contrib.optin": "はい、ニュースや更新のための私をサインアップしてください。",
      "record.contrib.age_gate.error": "申し訳ありませんが、ビデオを送信するために{age}以上でなければなりません。",
      "record.contrib.by_clicking_1": "このチェック・ボックスをオンにして、VideoGenieに同意します。",
      "record.contrib.tos": "ご利用条件およびプライバシー・ポリシー",
      "record.contrib.by_clicking_2": "投稿するビデオと関連する",
      "record.contrib.i_accept": "動画を投稿する",
      "record.success.thankyou": "ありがとうございました。",
      "record.success.we_ll_review": "すぐにビデオを確認し、ビデオが承認され次第お知らせします。",
      "record.vidinfo.almost_done": "後もう少しで完了です。ビデオを投稿して、あなたのアイデアを世界と共有しましょう。",
      "record.vidinfo.tag_a_friend": "友達にタグを付ける：",
      "record.vidinfo.video_title": "ビデオのタイトル：",
      "record.vidinfo.category": "カテゴリー：",
      "record.vidinfo.upload_video": "動画ファイルをアップロードする",
      "record.fbshare.meantime": "自分のビデオを友達と共有することもできます。",
      "record.fbshare.share_prompt": "あなたのアイデアを友達と共有しましょう。",
      "record.fbshare.caption": "Levi's FreeForumでアイデアを共有しました。",
      "record.fbshare.description": "何らかの形でアイデアを与えてくれた助言者や友達にメッセージを伝えるならいまです。あなたのメッセージを世界と共有しましょう。代わりにあなたが誰かにアイデアを与えることができる",
      "record.fbshare.record_your_own": "動画を作成する",

      "redirect.on": "オン",
      "redirect.facebook.campaign.description": "VideoGenieビデオ",


      "player.loading": "ロード中",
      "player.you_need_flash": "このビデオを再生するにはFlashが必要です。",
      "player.no_videos": "投稿されたビデオはまだありません。",
      "player.no_videos_in_cat": "このカテゴリーに投票されたビデオはありません。",
      "player.video_title": "タイトル：",
      "player.video_category": "カテゴリー：",

      "player.mansguide.wall": "ウォール",
      "player.mansguide.check_out": "ギャラリーをチェックする",
      "player.mansguide.record_your_own_link": "動画を作成する",
      "player.mansguide.record_your_own_header": "動画を作成する",
      "player.mansguide.video_gallery": "ビデオ・ギャラリー",
      "player.mansguide.all_videos": "すべてのビデオ",
      "player.mansguide.flag_confirm": "このビデオにフラグを付けますか",
      "player.mansguide.no_videos": "ビデオ・プレイヤーはここに表示されます。<br>現在、動画はありません。動画の作成、投稿をお願いします。",
      "player.mansguide.vote": "票獲得",
      "player.mansguide.votes": "票獲得",
      "player.mansguide.category": "カテゴリー",
      "player.mansguide.order": "表示",
      "player.mansguide.order.star": "ランダム",
      "player.mansguide.order.popularity": "最も人気のある",
      "player.mansguide.order.approval": "新着順",
      "player.mansguide.order.views": "閲覧数が多い",
      "player.mansguide.order.rating": "評価が高い",
      "player.mansguide.order.likes": "「いいね！」が多い",
      "player.mansguide.order.votes": "得票数が多い",

      "player.mansguide.friends_videos": "友達のビデオ",
      "player.mansguide.featured_videos": "注目ビデオ",
      "player.mansguide.all": "すべて",
      "player.mansguide.more": "さらに見る",
      "player.mansguide.page_number": "ページ {pageNumber}",
      "player.mansguide.loading_more": "ロード中",

      "powered_by": "Powered by VideoGenie",

      "record.help": "ヘルプ",
      "record.to_start": "録画を開始するには、「録画」をクリックしてください。",
      "record.stop": "停止",
      "record.re_rec": "再録画",
      "record.playback.stop": "停止",
      "record.playback.play": "再生",
      "record.blinker.recording": "録画中",
      "record.blinker.processing": "処理中",
      "record.blinker.buffering": "バッファー中",
      "record.try_again": "申し訳ありませんが、もう一度録画をやり直していただく必要があります。\n\n 原因としては、録画中の音量が低いことが考えられます。マイクを調整するか、より大きな声で話すようにしてください。",
      "record.seeyourself": "ここに自分自身が表示されない場合は、別のWebカメラを上のドロップダウン・メニューから選択する必要があります。\n\nそれ以外の場合は、右上の「ヘルプ」をクリックしてください。",
      "record.if_happy": "このままビデオを投稿する場合は、「次へ」をクリックして最後の手順に進んでください。",
      "record.welcome": "ビデオの記録はとても簡単です。",
      "record.instructions": "1. 「許可する」をクリックして、Webカメラをアクティブにします。\n2. ビデオを記録し、確認します。\n3. ビデオを投稿します。",
      "record.lets_get_started": "さあ始めましょう。",
      "record.record_label": "録画",
      "record.play_label": "再生",
      "record.next_label": "次へ",
      "record.error_label": "エラー",
      "record.no_camera": "カメラへのアクセスが拒否されているため、録画を開始することができません。Flash Playerによるカメラへのアクセスを許可してください。",
      "record.upload_video": "動画ファイルをアップロードする",
      "record.upload.reload_page": "再読み込みをして動画を作成してください。",
      "record.upload.or_upload_file": "または、既存の動画ファイルをアップロードしてください。（動画は{duration}以下、かつ4分以下）",
      "record.upload.submit_upload": "アップロード"
  }
}
